set encoding=utf-8
set nocompatible

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

set t_Co=256
set background=dark
colorscheme molokai

set ttyfast

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

